AllCops:
  Exclude:
    - 'train.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/ShadowingOuterLocalVariable:
  Enabled: false
  
Metrics/AbcSize:
  IgnoredMethods:
    - 'trains_by_type'
